### ISSUE TITLE
Feature Request: Close accounts

### ISSUE THREAD

**Issue by vnnv** [Eqonomize/Eqonomize#13]
Hi Hanna, 
Is it possible to add - Close Account Action. When an account is closed it should be moved in spearate group Close accounts. This group can be displayed bellow Expenses on the main page. Maybe it is good to have a constraint only accounts with total: 0.00 to be available for closing. 

Thanks, 
Victor

**Comment by hanna-kn** [comment]
It is already possible to mark an account as closed in the edit account window (although I now discovered, and fixed, that the check button was not properly updated). A closed account will still be shown in the list as usual if "Change" and "Total" are not zero for the selected period, otherwise it will be hidden.

**Comment by vnnv** [comment]
:) Maybe it's about time to update to the latest version (I still use KDE version). Thanks a lot :)

**Comment by vnnv** [comment]
Sorry to ask in closed thread, but is there any way from GUI to reopen closed account?

**Comment by hanna-kn** [comment]
At the moment, the only way to reopen a closed account is to select a period when the account was open/active and then change the status from the edit account window. Maybe it would be a good idea to add a reopen account (or manage accounts) option, which would open a window with a list of closed (or all) accounts and a reopen button, to the accounts menu.

**Comment by vnnv** [comment]
Sounds good 👍
