### ISSUE TITLE
problem when deleting an account

### ISSUE THREAD

**Issue by uprokop** [Eqonomize/Eqonomize#32]
I'm not sure if you got my last request, I answered directly to your last mail. To make sure, you get the message, I wirite again.

I installed version 1.0 on ubuntu 17.04.

I wanted to delete an account  because I finished the bank connection (without selecting the option to move the transactions to a different account). The account was empty. If the account is completely deleted, then some other accounts show wrong data. Not all, but some. Since I do not understand the error, I could not restore the data. This is a fatal error if you do not have a current backup.

Another tiny bug: the help-menu still shows beta-version 3.

**Comment by hanna-kn** [comment]
If I understand you correctly, you've closed a real world bank account and you therefore want to remove it from Eqonomize!. In that case you should _not_ delete the account even if it's _now_ empty. Instead the account should be marked as closed (at the bottom of the edit account dialog).

If you delete an account with associated past transactions, all those past transactions will be deleted both from the deleted account and other associated accounts (for transfers) and categories. A previously used account should under normal circumstances never be deleted since this erases all history of its existence. I should probably make this clearer in the application to avoid irreversible mistakes.

**Comment by hanna-kn** [comment]
> I'm not sure if you got my last request, I answered directly to your last mail. To make sure, you get the message, I wirite again.

You cannot answer github issue notification mails directly.

**Comment by uprokop** [comment]
Thank you! I I understood that now.
You must excuse: I am not very practised, both in computing and in english.

**Comment by baimafeima** [comment]
> I should probably make this clearer in the application to avoid irreversible mistakes.

Yeah, I think an additional confirmation button in the application would be great.
